// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAf5TQVZqH1Zmn5XJMKw4IesLAQlFKiUIg',
//     appId: '1:769755012205:web:7835bd4e35816c16e73364',
//     messagingSenderId: '769755012205',
//     projectId: 'sept2projectnew',
//     authDomain: 'sept2projectnew.firebaseapp.com',
//     storageBucket: 'sept2projectnew.appspot.com',
//     measurementId: 'G-38GVP6TX3Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyByLvDpI8_baGbs-X7HyllnxTuGHNJrmto',
//     appId: '1:769755012205:android:625788ccf86186f3e73364',
//     messagingSenderId: '769755012205',
//     projectId: 'sept2projectnew',
//     storageBucket: 'sept2projectnew.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBaTWticVQhKpbEVvoyt1qln-WZmCY8JPY',
//     appId: '1:769755012205:ios:daabcfc0d791198ae73364',
//     messagingSenderId: '769755012205',
//     projectId: 'sept2projectnew',
//     storageBucket: 'sept2projectnew.appspot.com',
//     iosBundleId: 'com.example.notepad',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBaTWticVQhKpbEVvoyt1qln-WZmCY8JPY',
//     appId: '1:769755012205:ios:2795b598b56025cee73364',
//     messagingSenderId: '769755012205',
//     projectId: 'sept2projectnew',
//     storageBucket: 'sept2projectnew.appspot.com',
//     iosBundleId: 'com.example.notepad.RunnerTests',
//   );
// }
